                                
                                    
                                /* BANCO DE DADOS NFL */


/* CRIAÇÃO DO BANCO DE DADOS, TODAS AS TABELAS E REGRAS */

CREATE DATABASE NFL;

USE NFL

CREATE TABLE TIMES(
    IDTIME INT,
    TIME VARCHAR(50) UNIQUE NOT NULL,
    FUNDACAO CHAR(4) NOT NULL,
    ESTADIO VARCHAR(50) NOT NULL
 );


ALTER TABLE TIMES ADD CONSTRAINT PK_TIME
PRIMARY KEY (IDTIME);


/* ALTERAR O NOME DA COLUNA NOME PARA TIME */
ALTER TABLE TIMES
CHANGE NOME TIME VARCHAR(50) UNIQUE NOT NULL; 


CREATE TABLE SUPERBOWL(
    IDSUPERBOWL INT UNIQUE,
    IDVENCEDOR INT NOT NULL,
    IDPERDEDOR INT NOT NULL,
    DATA DATE NOT NULL
);

ALTER TABLE SUPERBOWL ADD CONSTRAINT PK_JOGO_SUPERBOWL
PRIMARY KEY (IDSUPERBOWL)


ALTER TABLE SUPERBOWL ADD CONSTRAINT FK_TIME_VENCEDOR
FOREIGN KEY (IDVENCEDOR) REFERENCES TIMES (IDTIME);

ALTER TABLE SUPERBOWL ADD CONSTRAINT FK_TIME_PERDEDOR
FOREIGN KEY (IDPERDEDOR) REFERENCES TIMES (IDTIME);


CREATE TABLE JOGADORES(
    IDJOGADOR INT, 
    CAMISA INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    POSICAO VARCHAR(2) NOT NULL,
    IDADE INT NOT NULL,
    UNIVERSIDADE VARCHAR(50) NOT NULL,
    ID_TIME_JOGADOR INT NOT NULL
);




CREATE TABLE DIVISOES(
    ID_DIV_TIME INT NOT NULL,
    CONFERENCIA ENUM('AFC','NFC') NOT NULL,
    DIVISAO ENUM('East','North','South','West') NOT NULL 

);

ALTER TABLE DIVISOES ADD CONSTRAINT FK_DIVISAO_TIME
FOREIGN KEY (ID_DIV_TIME) REFERENCES TIMES (IDTIME);



CREATE TABLE AFC(
    ID_AFC INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    IDVENCEDOR INT NOT NULL,
    IDPERDEDOR INT NOT NULL,
    DATA INT(4) NOT NULL
);


ALTER TABLE AFC ADD CONSTRAINT FK_VENCEDOR_AFC
FOREIGN KEY (IDVENCEDOR) REFERENCES DIVISOES (ID_DIV_TIME);

ALTER TABLE AFC ADD CONSTRAINT FK_PERDEDOR_AFC
FOREIGN KEY (IDPERDEDOR) REFERENCES DIVISOES (ID_DIV_TIME);


CREATE TABLE NFC(
    ID_NFC INT PRIMARY KEY UNIQUE AUTO_INCREMENT,
    IDVENCEDOR INT NOT NULL,
    IDPERDEDOR INT NOT NULL,
    DATA INT(4) NOT NULL
);


ALTER TABLE NFC ADD CONSTRAINT FK_VENCEDOR_NFC
FOREIGN KEY (IDVENCEDOR) REFERENCES DIVISOES (ID_DIV_TIME);

ALTER TABLE NFC ADD CONSTRAINT FK_PERDEDOR_NFC
FOREIGN KEY (IDPERDEDOR) REFERENCES DIVISOES (ID_DIV_TIME);


/*ALTERACAO DA COLUNA POSICAO EM VARCHAR DE 50 PARA MUDAR NOMES*/

ALTER TABLE JOGADORES
CHANGE POSICAO POSICAO VARCHAR(50) NOT NULL;

UPDATE JOGADORES
SET POSICAO = 'Defensive End'
WHERE POSICAO = 'DE';

UPDATE JOGADORES
SET POSICAO = 'Quarterback'
WHERE POSICAO = 'QB';

UPDATE JOGADORES
SET POSICAO = 'Defensive Tackle'
WHERE POSICAO = 'DT';

UPDATE JOGADORES
SET POSICAO = 'Kicker'
WHERE POSICAO = 'K';

UPDATE JOGADORES
SET POSICAO = 'Offensive Guard'
WHERE POSICAO = 'OG';

UPDATE JOGADORES
SET POSICAO = 'Wide Receiver'
WHERE POSICAO = 'WR';

UPDATE JOGADORES
SET POSICAO = 'Running Back'
WHERE POSICAO = 'RB';

UPDATE JOGADORES
SET POSICAO = 'Offensive Tackle'
WHERE POSICAO = 'OT';

UPDATE JOGADORES
SET POSICAO = 'Linebacker'
WHERE POSICAO = 'LB';

UPDATE JOGADORES
SET POSICAO = 'Center'
WHERE POSICAO = 'C';

UPDATE JOGADORES
SET POSICAO = 'Long Snapper'
WHERE POSICAO = 'LS';

UPDATE JOGADORES
SET POSICAO = 'Punter'
WHERE POSICAO = 'P';

UPDATE JOGADORES
SET POSICAO = 'Defensive Back'
WHERE POSICAO = 'DB';

UPDATE JOGADORES
SET POSICAO = 'Tight End'
WHERE POSICAO = 'TE';

UPDATE JOGADORES
SET POSICAO = 'Defensive Line'
WHERE POSICAO = 'DL';

UPDATE JOGADORES
SET POSICAO = 'Offensive Line'
WHERE POSICAO = 'OL';


ALTER TABLE JOGADORES ADD CONSTRAINT PK_JOGADOR
PRIMARY KEY (IDJOGADOR);

ALTER TABLE JOGADORES 
MODIFY IDJOGADOR INT AUTO_INCREMENT;

ALTER TABLE JOGADORES ADD CONSTRAINT FK_JOGADOR_TIME
FOREIGN KEY (ID_TIME_JOGADOR) REFERENCES TIMES (IDTIME);


CREATE TABLE TEMPORADAS(
    IDTEMPORADA INT UNIQUE
);

ALTER TABLE TEMPORADAS ADD CONSTRAINT PK_TEMPORADA
PRIMARY KEY (IDTEMPORADA);


CREATE TABLE JOGOS(
    IDJOGOS INT PRIMARY KEY AUTO_INCREMENT,
    ID_TIME INT NOT NULL, 
    VITORIAS INT NOT NULL,
    DERROTAS INT NOT NULL,
    EMPATES INT NOT NULL,
    ID_TEMPORADA INT NOT NULL
);

ALTER TABLE JOGOS ADD CONSTRAINT FK_JOGOS_TIME
FOREIGN KEY (ID_TIME) REFERENCES TIMES (IDTIME);

ALTER TABLE JOGOS ADD CONSTRAINT FK_JOGOS_TEMPORADA
FOREIGN KEY (ID_TEMPORADA) REFERENCES TEMPORADAS (IDTEMPORADA);